apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: jenkins
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: jenkins-volume
          mountPath: /mnt/jenkins
  volumes:
    - name: jenkins-volume
      persistentVolumeClaim:
        claimName: efs-pvc
